version: '3.0'
services:
      nginx:
          build:
              context: ./dockerfiles/nginx/portainer
              args:
                  - DNS_PORTAINER=${DNS_PORTAINER}
                  - IP_PORTAINER=172.46.0.11
          depends_on:
              - portainer
          links:
              - portainer
          networks:
              portainer-network:
                  ipv4_address: 172.46.0.10


      portainer:
          image: portainer/portainer
          volumes:
              - /var/run/docker.sock:/var/run/docker.sock
              - /opt/portainer/data:/data
          restart: always
          networks:
              portainer-network:
                  ipv4_address: 172.46.0.11

networks:
  portainer-network:
     ipam:
         config:
             - subnet: 172.46.0.0/24
